name: Java CI

on:
    push:
        branches:
            # main and dev versions for each mc ver here
            - "main"
    workflow_dispatch:
        inputs:
            norelease:
                description: 'Do not publish'
                required: true
                default: 'false'

jobs:
    build:
        runs-on: ubuntu-latest
        if: |
            !contains(github.event.head_commit.message, '[ci skip]')
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 30 # Gets the last 30 commits so the changelog might work
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '17'
            -   name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v1
            -   name: Build and Publish with Gradle
                uses: gradle/gradle-build-action@v2
                env:
                    SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
                with:
                    arguments: build -x test publish --stacktrace --no-daemon